all:
  children:
    database:
      hosts:
        db.local:
          ansible_connection: ssh
          ansible_host: db.local
          ansible_user: root
          ansible_password: pwd
          ansible_become: true
          ansible_become_method: su
          ansible_become_user: oracle
    bo:
      children:
        bo_cluster_a:
          hosts:
            bo.cluster_a.local:
              ansible_connection: ssh
              ansible_host: bo.cluster_a.local
              ansible_user: root
              ansible_password: pwd
        bo_cluster_b:
          hosts:
            bo.cluster_b.local:
              ansible_connection: ssh
              ansible_host: bo.cluster_b.local
              ansible_user: root
              ansible_password: pwd
    webapp:
      hosts:
        app.local:
          ansible_connection: ssh
          ansible_host: app.local
          ansible_user: root
          ansible_password: pwd
        app2.local:
          ansible_connection: ssh
          ansible_host: app2.local
          ansible_user: root
          ansible_password: pwd
    scheduler:
      children:
        scheduler_master:
          hosts:
            sch.master.local:
              ansible_connection: ssh
              ansible_host: sch.master.local
              ansible_user: root
              ansible_password: pwd
        scheduler_slave:
          hosts:
            sch.slave.local:
              ansible_connection: ssh
              ansible_host: sch.slave.local
              ansible_user: root
              ansible_password: pwd
            sch2.slave.local:
              ansible_connection: ssh
              ansible_host: sch2.slave.local
              ansible_user: root
              ansible_password: pwd
    executor:
      children:
        executor_cluster_a:
          hosts:
            exe.cluster_a.local:
              ansible_connection: ssh
              ansible_host: exe.cluster_a.local
              ansible_user: root
              ansible_password: pwd
            exe2.cluster_a.local:
              ansible_connection: ssh
              ansible_host: exe2.cluster_a.local
              ansible_user: root
              ansible_password: pwd
        executor_cluster_b:
          hosts:
            exe.cluster_b.local:
              ansible_connection: ssh
              ansible_host: exe.cluster_b.local
              ansible_user: root
              ansible_password: pwd
            exe2.cluster_b.local:
              ansible_connection: ssh
              ansible_host: exe2.cluster_b.local
              ansible_user: root
              ansible_password: pwd
