all:
  children:
    database:
      hosts:
        db.local:
      vars:
        ansible_connection: ssh
        ansible_host: db.local
        ansible_user: root
        ansible_become: true
        ansible_become_method: su
        ansible_become_user: oracle

    bo:
      children:
        bo_cluster_a:
          hosts:
            bo.cluster_a.local:
        bo_cluster_b:
          hosts:
            bo.cluster_b.local:
      vars:
        ansible_connection: docker

    webapp:
      hosts:
        app.local:
      vars:
        ansible_connection: docker

    scheduler:
      children:
        scheduler_master:
          hosts:
            sch.master.local:

        scheduler_slave:
          hosts:
            sch.slave.local:
      vars:
        ansible_connection: docker

    executor:
      children:
        executor_cluster_a:
          hosts:
            exe.cluster_a.local:

        executor_cluster_b:
          hosts:
            exe.cluster_b.local:
      vars:
        ansible_connection: docker
