---
- name: restart the scheduler's jboss service
  hosts: scheduler_master
  roles:
    - role: jboss/restart
    
- name: shutdown the scheduler's jboss service
  hosts: scheduler_slave
  roles:
    - role: jboss/restart

- name: restart the executor's jboss service
  hosts: executor
  roles:
    - role: jboss/restart

- name: restart the webapp's jboss service
  hosts: webapp
  roles:
    - role: jboss/restart

