---
- name: shutdown the webapp's jboss service
  hosts: webapp
  roles:
    - role: jboss/shutdown

- name: shutdown the executor's jboss service
  hosts: executor
  roles:
    - role: jboss/shutdown

- name: shutdown the scheduler's jboss service
  hosts: scheduler_slave
  roles:
    - role: jboss/shutdown

- name: shutdown the scheduler's jboss service
  hosts: scheduler_master
  roles:
    - role: jboss/shutdown
	
